dataset:
  start_time: '2021-08-30'
  end_time: '2022-08-26'
  segments: {
    'train': ['2021-08-30', '2022-02-28'],
    'valid': ['2022-02-29', '2022-05-31'],
    'test': ['2022-06-01', '2022-08-26']
  }

model:
  name: 'DoubleEnsemble'
  params: {
    'base_model': 'gbm',
    'loss': 'mse',
    'num_models': 6,
    'enable_sr': True,
    'enable_fs': True,
    'alpha1': 1,
    'alpha2': 1,
    'bins_sr': 10,
    'bins_fs': 5,
    'decay': 0.5,
    'sample_ratios': [0.8, 0.7, 0.6, 0.5, 0.4],
    'sub_weights': [1, 1, 1, 1, 1, 1],
    'num_boost_round': 200,
    'early_stopping_rounds': 50,
    'colsample_bytree': 0.8879,
    'learning_rate': 0.1,
    'subsample': 0.8789,
    'max_depth': 8,
    'num_leaves': 32,
    'num_threads': 4,
    'metric': 'rmse',
    'verbosity': -1
  }
