dataset:
  segments: {
    'train': ['2021-08-30', '2022-04-28'],
    'valid': ['2022-04-29', '2022-08-26']
  }

model:
  name: 'LGB'
  params: {
    'objective': 'mse',
    'learning_rate': 0.2,
    'colsample_bytree': 0.8879,
    'max_depth': 8,
    'num_leaves': 210,
    'subsample': 0.8789,
    'lambda_l1': 205.6999,
    'lambda_l2': 580.9768,
    'metric': 'rmse',
    'nthread': 4
  }
