dataset:
  segments: {
    'train': ['2021-08-30', '2022-04-28'],
    'valid': ['2022-04-29', '2022-08-26']
  }

model:
  params: {
    'objective': 'reg:squarederror',
    'eta': 0.0421,
    'colsample_bytree': 0.8879,
    'max_depth': 8,
    'subsample': 0.8789,
    'nthread': 2,
    'eval_metric': 'rmse'
  }
