dataset:
  start_time: '2012-01-01'
  end_time: '2023-05-01'
  segments: {
    'train': [ '2012-07-01', '2021-12-31' ],
    'valid': [ '2022-01-01', '2022-11-31' ],
    'test': [ '2023-01-01', '2023-05-01' ]
  }

model:
  name: 'XGB'
  params: {
    'objective': 'reg:squarederror',
    'eta': 0.0421,
    'tree_method': 'hist',
    'colsample_bytree': 0.8879,
    'max_depth': 8,
    'subsample': 0.8789,
    'reg_alpha': 10,
    'reg_lambda': 10,
    'eval_metric': 'rmse',
    'nthread': 4
  }
